version: '3'

tasks:
  build:
    desc: Build the go binary.
    cmds:
      - go build -ldflags "-w -s" -o ./cmd/rusprofile/rusprofile.exe ./cmd/rusprofile/main.go
    silent: true
  gen:
    desc: Generate api from proto files.
    cmds:
      - protoc -I $GOPATH\\protoc\\include -I. -I $GOPATH/src -I $GOPATH\\pkg\\mod\\github.com\\grpc-ecosystem\\grpc-gateway@v1.16.0\\third_party\\googleapis -I $GOPATH\\pkg\\mod\\github.com\\grpc-ecosystem\\grpc-gateway --grpc-gateway_out=logtostderr=true:. --go_out=. --go-grpc_out=. --swagger_out=allow_merge=true,merge_file_name=api:.\\doc .\\api\\rusprofile.proto
    silent: true
  docker:
    desc: Build image and run into Docker.
    cmds:
      - docker stop test_task && docker rm -f test_task
      - docker build -t test_task -f ./docker/Dockerfile .
      - docker run -d -p 8080:8080 -p 8081:8081 --name test_task test_task
    silent: true
