// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: api/rusprofile.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestPersonalData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Inn string `protobuf:"bytes,1,opt,name=inn,proto3" json:"inn,omitempty"`
}

func (x *RequestPersonalData) Reset() {
	*x = RequestPersonalData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rusprofile_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestPersonalData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPersonalData) ProtoMessage() {}

func (x *RequestPersonalData) ProtoReflect() protoreflect.Message {
	mi := &file_api_rusprofile_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPersonalData.ProtoReflect.Descriptor instead.
func (*RequestPersonalData) Descriptor() ([]byte, []int) {
	return file_api_rusprofile_proto_rawDescGZIP(), []int{0}
}

func (x *RequestPersonalData) GetInn() string {
	if x != nil {
		return x.Inn
	}
	return ""
}

type ResponsePersonalData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Inn string `protobuf:"bytes,1,opt,name=inn,proto3" json:"inn,omitempty"`
	Kpp string `protobuf:"bytes,2,opt,name=kpp,proto3" json:"kpp,omitempty"`
	Ceo string `protobuf:"bytes,3,opt,name=ceo,proto3" json:"ceo,omitempty"`
}

func (x *ResponsePersonalData) Reset() {
	*x = ResponsePersonalData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rusprofile_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponsePersonalData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponsePersonalData) ProtoMessage() {}

func (x *ResponsePersonalData) ProtoReflect() protoreflect.Message {
	mi := &file_api_rusprofile_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponsePersonalData.ProtoReflect.Descriptor instead.
func (*ResponsePersonalData) Descriptor() ([]byte, []int) {
	return file_api_rusprofile_proto_rawDescGZIP(), []int{1}
}

func (x *ResponsePersonalData) GetInn() string {
	if x != nil {
		return x.Inn
	}
	return ""
}

func (x *ResponsePersonalData) GetKpp() string {
	if x != nil {
		return x.Kpp
	}
	return ""
}

func (x *ResponsePersonalData) GetCeo() string {
	if x != nil {
		return x.Ceo
	}
	return ""
}

var File_api_rusprofile_proto protoreflect.FileDescriptor

var file_api_rusprofile_proto_rawDesc = []byte{
	0x0a, 0x14, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x75, 0x73, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x72, 0x75, 0x73, 0x70, 0x72, 0x6f, 0x66, 0x69,
	0x6c, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x27, 0x0a, 0x13, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x65,
	0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x6e,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x69, 0x6e, 0x6e, 0x22, 0x4c, 0x0a, 0x14,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x6e, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x69, 0x6e, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x70, 0x70, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x70, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x65, 0x6f, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x65, 0x6f, 0x32, 0x85, 0x01, 0x0a, 0x11, 0x52,
	0x75, 0x73, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x70, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x22, 0x2e, 0x72, 0x75,
	0x73, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x1a,
	0x23, 0x2e, 0x72, 0x75, 0x73, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c,
	0x44, 0x61, 0x74, 0x61, 0x22, 0x1c, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x16, 0x12, 0x14, 0x2f, 0x72,
	0x75, 0x73, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x7b, 0x69, 0x6e,
	0x6e, 0x7d, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_rusprofile_proto_rawDescOnce sync.Once
	file_api_rusprofile_proto_rawDescData = file_api_rusprofile_proto_rawDesc
)

func file_api_rusprofile_proto_rawDescGZIP() []byte {
	file_api_rusprofile_proto_rawDescOnce.Do(func() {
		file_api_rusprofile_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_rusprofile_proto_rawDescData)
	})
	return file_api_rusprofile_proto_rawDescData
}

var file_api_rusprofile_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_rusprofile_proto_goTypes = []interface{}{
	(*RequestPersonalData)(nil),  // 0: rusprofile.v1.RequestPersonalData
	(*ResponsePersonalData)(nil), // 1: rusprofile.v1.ResponsePersonalData
}
var file_api_rusprofile_proto_depIdxs = []int32{
	0, // 0: rusprofile.v1.RusprofileService.GetData:input_type -> rusprofile.v1.RequestPersonalData
	1, // 1: rusprofile.v1.RusprofileService.GetData:output_type -> rusprofile.v1.ResponsePersonalData
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_rusprofile_proto_init() }
func file_api_rusprofile_proto_init() {
	if File_api_rusprofile_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_rusprofile_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestPersonalData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rusprofile_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponsePersonalData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_rusprofile_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_rusprofile_proto_goTypes,
		DependencyIndexes: file_api_rusprofile_proto_depIdxs,
		MessageInfos:      file_api_rusprofile_proto_msgTypes,
	}.Build()
	File_api_rusprofile_proto = out.File
	file_api_rusprofile_proto_rawDesc = nil
	file_api_rusprofile_proto_goTypes = nil
	file_api_rusprofile_proto_depIdxs = nil
}
