// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RusprofileServiceClient is the client API for RusprofileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RusprofileServiceClient interface {
	GetData(ctx context.Context, in *RequestPersonalData, opts ...grpc.CallOption) (*ResponsePersonalData, error)
}

type rusprofileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRusprofileServiceClient(cc grpc.ClientConnInterface) RusprofileServiceClient {
	return &rusprofileServiceClient{cc}
}

func (c *rusprofileServiceClient) GetData(ctx context.Context, in *RequestPersonalData, opts ...grpc.CallOption) (*ResponsePersonalData, error) {
	out := new(ResponsePersonalData)
	err := c.cc.Invoke(ctx, "/rusprofile.v1.RusprofileService/GetData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RusprofileServiceServer is the server API for RusprofileService service.
// All implementations must embed UnimplementedRusprofileServiceServer
// for forward compatibility
type RusprofileServiceServer interface {
	GetData(context.Context, *RequestPersonalData) (*ResponsePersonalData, error)
	mustEmbedUnimplementedRusprofileServiceServer()
}

// UnimplementedRusprofileServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRusprofileServiceServer struct {
}

func (UnimplementedRusprofileServiceServer) GetData(context.Context, *RequestPersonalData) (*ResponsePersonalData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetData not implemented")
}
func (UnimplementedRusprofileServiceServer) mustEmbedUnimplementedRusprofileServiceServer() {}

// UnsafeRusprofileServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RusprofileServiceServer will
// result in compilation errors.
type UnsafeRusprofileServiceServer interface {
	mustEmbedUnimplementedRusprofileServiceServer()
}

func RegisterRusprofileServiceServer(s grpc.ServiceRegistrar, srv RusprofileServiceServer) {
	s.RegisterService(&RusprofileService_ServiceDesc, srv)
}

func _RusprofileService_GetData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestPersonalData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RusprofileServiceServer).GetData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rusprofile.v1.RusprofileService/GetData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RusprofileServiceServer).GetData(ctx, req.(*RequestPersonalData))
	}
	return interceptor(ctx, in, info, handler)
}

// RusprofileService_ServiceDesc is the grpc.ServiceDesc for RusprofileService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RusprofileService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rusprofile.v1.RusprofileService",
	HandlerType: (*RusprofileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetData",
			Handler:    _RusprofileService_GetData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/rusprofile.proto",
}
